#! /bin/bash

echo "get macros"
[ -d m4 ] || mkdir m4
for i in ax_compiler_vendor ax_compiler_version ; do
  [ -f m4/$i.m4 ] || wget "http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/$i.m4" --output-document=m4/$i.m4
done

echo "update configure.ac, etc"
autoreconf --install --warnings=all --include=m4 "$@"
