#!/bin/sh
# from https://github.com/git/git/blob/master/GIT-VERSION-GEN
# modified to suit, 2023 A. Boyle
# License: GPL2

GVF=${1:-.version}
DEF_VER=UNKNOWN

LF='
'

# First see if there is a version file (included in release tarballs),
# then try git-describe, then default.
if test -f .tarball-version
then
    VN=$(cat .tarball-version) || VN="$DEF_VER"
elif test -d ${GIT_DIR:-.git} -o -f .git &&
    VN=$(git describe --match "v[0-9]*" HEAD 2>/dev/null) &&
    case "$VN" in
    *$LF*) (exit 1) ;;
    v[0-9]*)
        git update-index -q --refresh
        test -z "$(git diff-index --name-only HEAD --)" ||
        VN="$VN-dirty" ;;
    esac
then
    VN=$(echo "$VN" | sed -e 's/-\([0-9]\)/.\1/g');
else
    VN="$DEF_VER"
fi

VN=$(expr "$VN" : v*'\(.*\)')

if test -r $GVF
then
    VC=$(sed -e 's/^GIT_VERSION = //' <$GVF)
else
    VC=unset
fi
test "$VN" = "$VC" || {
    echo >&2 "GIT_VERSION = $VN"
    echo "GIT_VERSION = $VN" >$GVF
}
